19766: Adds support for clone_entity and set_random_seed
howsoai/amalgam-lang-py pull request #69
Opened 2024-03-22 23:28 UTC by howsohazard

2024-03-23 14:44 UTC, mkoistinen approved these changes
Looks great. I left some minor recommendations, but otherwise approved.

2024-03-23 14:44 UTC, mkoistinen commented on amalgam/api.py
> +            f"CLONE_ENTITY \"{self.escape_double_quotes(handle)}\" "
This would be more readable if you used single quotes on the outer string as you can then avoid backslashes:
```
... = (
    f'CLONE_ENTITY "{self.escape_double_quotes(handle)}" '
    f'"{self.escape_double_quotes(clone_handle)}" '
    f'"{self.escape_double_quotes(amlg_path)}" {str(persist).lower()} '
    f'"{write_log}" "{print_log}"'
)

2024-03-23 14:44 UTC, mkoistinen commented on amalgam/api.py
> +        self._log_execution(f"SET_RANDOM_SEED \"{self.escape_double_quotes(handle)}\""
Use `'` on the outer string to avoid `\`.

2024-03-25 15:17 UTC, cademack requested changes

2024-03-25 15:17 UTC, cademack commented on amalgam/api.py
> +        load_command_log_entry = (
nitpicky, but this variable name should probably be updated

2024-03-25 15:17 UTC, cademack commented on amalgam/api.py
> +        Sets an entity's random seed
missing period here

2024-03-25 15:17 UTC, cademack commented on amalgam/api.py
> +        bool
This method isn't actually returning anything. Not sure if the docstring/type hint needs updating or the logic.

2024-03-25 16:27 UTC, cademack approved these changes

2024-03-25 16:35 UTC, howsoRes approved these changes

2024-03-25 17:09 UTC, merged