20241: Adjusts type hints
howsoai/amalgam-lang-py pull request #96
Opened 2024-06-10 19:49 UTC by apbassett

Follow-up to unresolved comments in #94.

2024-06-10 19:51 UTC, apbassett commented on amalgam/api.py
@mkoistinen question from @jdbeel about `_log_reply` on line 513:

Is this actually Any? or is it bytes? AnyStr?

``` def _log_reply(self, reply: t.Any):
        """
        Log a raw reply from the amalgam process.
        Uses a pre-pended '#RESULT >' so it can be filtered by tools like grep.
        Parameters
        ----------
        reply : Any
            The raw reply string to log.
        """
```

2024-06-10 21:12 UTC, mkoistinen requested changes

2024-06-10 21:12 UTC, mkoistinen commented on amalgam/api.py
> +    cast, cdll, POINTER, Structure, _Pointer
Please keep this alphabetized.

2024-06-10 21:12 UTC, fulpm commented on amalgam/api.py
> +    def __init__(self, api: Amalgam, c_status: t.Optional[_LoadEntityStatus] = None):
Should instead be renamed.

2024-06-10 21:13 UTC, mkoistinen commented on amalgam/api.py
It's probably `str | bytes`.

2024-06-10 21:19 UTC, fulpm commented on amalgam/api.py
The value is stringified so it could be `Any` value. In fact looks like the LoadEntityStatus is passed in to this as well as numbers, etc

2024-06-10 21:21 UTC, fulpm commented on amalgam/api.py
> +    def char_p_to_bytes(self, p: _Pointer[c_char]) -> bytes:
Looks like the return of this method could also be None. Additionally, lets rename the variable used below, its shadow naming the `bytes` global.

2024-06-10 21:22 UTC, fulpm commented on amalgam/api.py
>          return buf
Looks like this should be typed to return `ctypes.Array[c_char]`

2024-06-10 21:37 UTC, fulpm commented on amalgam/api.py
> +        bytes_string
```suggestion
        bytes or None
```

2024-06-10 21:39 UTC, fulpm commented on amalgam/api.py
> +        bytes_str = cast(p, c_char_p).value
Looking at this again, we cast the parameter to `c_char_p` seems like it should just be typed as such in the method signature. Then we wont need the `_Pointer` type at all. (Will need to update docstring too)

2024-06-10 21:40 UTC, fulpm commented on amalgam/api.py
> +    def char_p_to_bytes(self, p: _Pointer[c_char]) -> bytes:
Due to the return type change, review any methods that call this internally to make sure their return type is also `bytes | None`

2024-06-10 21:42 UTC, fulpm reviewed
Looks like we use `argtype` in a lot of places, but the correct attribute is `argtypes`

2024-06-10 21:43 UTC, fulpm commented on amalgam/api.py
> +    ) -> Array[c_char]:
Need to update docstring for return type.

2024-06-11 15:01 UTC, mkoistinen approved these changes

2024-06-11 15:07 UTC, fulpm commented on amalgam/api.py
> +    _Pointer, Array, byref, c_bool, c_char, c_char_p, c_double, c_size_t, c_uint64, c_void_p,
```suggestion
    Array, byref, c_bool, c_char, c_char_p, c_double, c_size_t, c_uint64, c_void_p,
```

2024-06-11 15:09 UTC, fulpm commented on amalgam/api.py
> +        bytes_str = cast(p, c_char_p).value
Type should be `c_char_p` not `char_p` and the cast can be removed. (need to update docstring too)

2024-06-11 15:40 UTC, fulpm commented on amalgam/api.py
>          self.amlg.DeleteString.argtypes = c_char_p,
```suggestion
        self.amlg.DeleteString.argtypes = [c_char_p]
```

2024-06-11 15:42 UTC, fulpm approved these changes

2024-06-11 15:47 UTC, merged